name: orm
services:
  postgres-drizzle:
    image: "postgres:16"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - "7005:5432"
  postgres-prisma:
    image: "postgres:16"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - "7006:5432"
  postgres-sequelize:
    image: "postgres:16"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - "7007:5432"
